[package]
name = "study"
version = "0.1.0"
authors = ["徐伟展 <xuweizhan@zmeng123.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
